version: '3'
services:

    web:
        build: .
        restart: always
        env_file:
          - .env
        ports:
            - "8000:8000"
        depends_on:
            - db

    db:
        container_name: postgres
        build:
            context: .
            dockerfile: Dockerfile-Postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=dev
            - POSTGRES_USER=dev
            - POSTGRES_DB=wrdb
        # command: psql -U dev -c "create database wrdb"
        volumes:
            - db:/data/db

volumes:
    db: