version: '3'
services:

    web:
        build: .
        restart: always
        env_file:
          - .env
        ports:
            - "8000:8000"
        depends_on:
            - db

    db:
        container_name: mongo
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - db:/data/db

volumes:
    db: